# Generated by Django 3.0.5 on 2020-07-14 20:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_titles', '0003_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('score', models.SmallIntegerField(validators=[django.core.
                                                               validators.
                                                               MinValueValidator(1),
                                                   django.core.validators.
                                                   MaxValueValidator(10)])),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.
                                             deletion.CASCADE,
                                             related_name='author',
                                             to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.
                                            deletion.CASCADE,
                                            related_name='reviews',
                                            to='api_titles.Title')),
            ],
        ),
    ]
